### ISSUE TITLE
[FE] 응급실 추천 서비스 UI/UX 개선

### ISSUE THREAD

**Issue by jiva-z** [Emergency-Service/Executable_Code#6]
## 개요
응급실 추천 서비스의 사용자 인터페이스를 개선하고 반응형 디자인을 적용하여 사용성을 향상시킵니다.

## 주요 변경사항

**1. 헤더 디자인 개선**
- 로고 및 슬로건 이미지 배치 최적화
- 검색바 디자인 현대화
- 반응형 햄버거 메뉴 추가

**2. 메인 콘텐츠 레이아웃**
- 카드 형태의 정보 표시
- 그림자 효과로 시각적 깊이감 추가
- 여백과 간격 최적화

**3. 모바일 대응**
- 반응형 테이블 레이아웃
- 터치 친화적 UI 요소

**4. 푸터 기능**
- 개인정보처리방침
- 이용약관
- 고객센터
- 문의하기 모달 구현

## 스타일 개선사항

**1. 색상 체계**
```css
:root {
    --primary-color: #4A90E2;
    --secondary-color: #82B1FF;
    --accent-color: #2962FF;
    --background-color: #F5F7FA;
    --text-color: #2C3E50;
    --border-color: #E1E8ED;
}
```

**2. 반응형 브레이크포인트**
- Desktop: 1200px 이상
- Tablet: 768px ~ 1199px
- Mobile: 480px 이하

**3. 접근성 개선**
- 적절한 폰트 크기
- 충분한 여백과 터치 영역
- 시각적 피드백 강화

## 모달 기능
- 개인정보처리방침
- 이용약관
- 고객센터
- 문의하기 인터페이스

## 추가된 스크립트 기능
- 모달 창 제어
- 모바일 메뉴 제어
- 반응형 레이아웃 처리

## 브라우저 호환성
- 모던 브라우저 지원
- IE11 이상 호환성 보장
- 모바일 브라우저 최적화
